name: app-test

on:
  push:
    branches: [main]
    paths:
      - '**'
      - '!*.md'
      - '!LICENSE'
      - '!.github/**'
      - '.github/workflows/app-test.yml'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  app-test:
    runs-on: ${{ matrix.os }}
    name: Test Node.js ${{ matrix.node_version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node_version: ['24']
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install xvfb
        if: runner.os == 'Linux'
        run: |
          sudo apt install -y -q --no-install-recommends xvfb

      - uses: actions/setup-node@v4
        with:
          # choose node.js version to use
          node-version: ${{ matrix.node_version }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci

      # run test
      - name: Test module script (Windows or macOS)
        if: runner.os != 'Linux'
        run: |
          npm run test

      - name: Test module script (Linux)
        if: runner.os == 'Linux'
        run: |
          npm run test:linux
